version: "3.7"

services:

  postgres:
    container_name: 'recommender-backend-db'
    image: 'postgres:latest'
    restart: always
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=masamonoke'
      - 'POSTGRES_DB=recommender-backend'
      - 'POSTGRES_PASSWORD=password'

  redis:
      image: redis/redis-stack
      volumes:
        - redis_data:/data:rw
      ports:
        - 6379:6379
      restart: unless-stopped

volumes:
  redis_data:
